#!/bin/bash -e

source /usr/lib/grub/grub-mkconfig_lib

if [ "$GRUB_TERMINAL_OUTPUT" = "gfxterm" ] ; then
  # Jo Shield's theme
    prepare_grub_to_access_device $(${grub_probe} --target=device /boot/grub)
    relpath=$(make_system_path_relative_to_its_root /boot/grub)
  cat << EOF
insmod png
loadfont ${relpath}/dejavu_sans_10.pf2
loadfont ${relpath}/dejavu_sans_12.pf2
loadfont ${relpath}/dejavu_sans_bold_14.pf2
EOF
fi

# fallback to traditional Debian blue theme
cat << EOF
set menu_color_normal=cyan/blue
set menu_color_highlight=white/blue
EOF
