#!/bin/bash -e

source /usr/lib/grub/grub-mkconfig_lib

# Tell Linux loader that switching back to text mode before
# transferring control to Linux is not necessary (which
# is true for Debian Linux packages).
echo "set gfxpayload=keep"

if [ "$GRUB_TERMINAL_OUTPUT" = "gfxterm" ] ; then
  # Jo Shield's theme
  cat << EOF
insmod png
loadfont /boot/grub/dejavu_sans_10.pf2
loadfont /boot/grub/dejavu_sans_12.pf2
loadfont /boot/grub/dejavu_sans_bold_14.pf2
EOF
fi

# fallback to traditional Debian blue theme
cat << EOF
set menu_color_normal=cyan/blue
set menu_color_highlight=white/blue
EOF
