obj/grub-rescue-pc/grub-core/pxeboot.img		usr/lib/grub-rescue
obj/grub-rescue-pc/grub-core/boot.img			usr/lib/grub-rescue
obj/grub-rescue-pc/grub-core/kernel.img			usr/lib/grub-rescue
obj/grub-rescue-pc/grub-core/lnxboot.img		usr/lib/grub-rescue
obj/grub-rescue-pc/grub-core/boot_hybrid.img		usr/lib/grub-rescue
obj/grub-rescue-pc/grub-core/lzma_decompress.img	usr/lib/grub-rescue
obj/grub-rescue-pc/grub-core/diskboot.img		usr/lib/grub-rescue
obj/grub-rescue-pc/grub-core/cdboot.img			usr/lib/grub-rescue
